### ISSUE TITLE
URL shortener (hasher)

### ISSUE THREAD

**Issue by Fingercomp** [hel-repo/hel#6]
### Details
We need some kind of URL shortener for statistics.

### TODO

- [ ] Choose & create a route.
- [ ] Create a DB collection.
- [ ] Implement URL hashing algorithm.
- [ ] Implement URL hash resolver.
- [ ] Implement a controller for the route.
- [ ] Collect statistics.

**Comment by Fingercomp** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Сокращатель ссылок](https://trello.com/c/gxFUzK16/116--)

**Comment by Fingercomp** [comment]
As we've figured out, the URL hasher isn't really a solution to the problem. I'm closing the issue for now.
